### PR TITLE
apply rate limit by IP

### PR DESCRIPTION
**Pull request by jpeerz**

### CODE REVIEW

**Comment by rcpeters** [comment]
Cool. We should also figure out excluding static content. Anything not `.*/details.*` or `.*/edit.*`. might work well.

**Comment by rcpeters** [comment]
This caches everything including the dynamic pages.

**Comment by jpeerz** [comment]
[Reconfigure SMID app - NGINX setup](https://trello.com/c/7zUDkq7l/3704-reconfigure-smid-app-nginx-setup)

**Comment by rcpeters** [comment]
This would still cache everything including dynamic pages? It also rate limits all request(which we should only rate limit dynamic pages)?

**Comment by rcpeters** [comment]
Let's give it a go! @lizkrznarich can you test when @jpeerz pushed it out.

**Pull request merged**
